'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WsUsuario
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsUsuario.WSbuscarUsuarioSoap")>  _
    Public Interface WSbuscarUsuarioSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WSlistadoUsuarios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WSlistadoUsuarios() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WSlistadoUsuarios", ReplyAction:="*")>  _
        Function WSlistadoUsuariosAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WSlistadoUsuarioNombre", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function WSlistadoUsuarioNombre(ByVal user As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WSlistadoUsuarioNombre", ReplyAction:="*")>  _
        Function WSlistadoUsuarioNombreAsync(ByVal user As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSbuscarUsuarioSoapChannel
        Inherits WsUsuario.WSbuscarUsuarioSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSbuscarUsuarioSoapClient
        Inherits System.ServiceModel.ClientBase(Of WsUsuario.WSbuscarUsuarioSoap)
        Implements WsUsuario.WSbuscarUsuarioSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements WsUsuario.WSbuscarUsuarioSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements WsUsuario.WSbuscarUsuarioSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Function WSlistadoUsuarios() As System.Data.DataSet Implements WsUsuario.WSbuscarUsuarioSoap.WSlistadoUsuarios
            Return MyBase.Channel.WSlistadoUsuarios
        End Function
        
        Public Function WSlistadoUsuariosAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsUsuario.WSbuscarUsuarioSoap.WSlistadoUsuariosAsync
            Return MyBase.Channel.WSlistadoUsuariosAsync
        End Function
        
        Public Function WSlistadoUsuarioNombre(ByVal user As String) As System.Data.DataSet Implements WsUsuario.WSbuscarUsuarioSoap.WSlistadoUsuarioNombre
            Return MyBase.Channel.WSlistadoUsuarioNombre(user)
        End Function
        
        Public Function WSlistadoUsuarioNombreAsync(ByVal user As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsUsuario.WSbuscarUsuarioSoap.WSlistadoUsuarioNombreAsync
            Return MyBase.Channel.WSlistadoUsuarioNombreAsync(user)
        End Function
    End Class
End Namespace
